### ISSUE TITLE
undefined method `notifications_present?' for nil:NilClass after upgrading from 4.9.0 to 4.11.1

### ISSUE THREAD

**Issue by monfresh** [flyerhzm/bullet#168]
Hi,

bullet 4.9.0 was working fine in my Rails 4.0.4 app, but when I upgraded bullet to 4.11.1, now some of my specs are throwing this error:

```
undefined method `notifications_present?' for nil:NilClass
```

Does 4.11.1 introduce changes to the test setup that aren't documented? Specifically, it's complaining about this line in my `config.after(:each)` block in the RSpec configuration:

```
Bullet.perform_out_of_channel_notifications if Bullet.enable? && Bullet.notification?
```

Thanks for any help you can provide.
