### ISSUE TITLE
Error: undefined method `has_cached_counter?' in ActiveRecord 3.2.x for HABTM associations

### ISSUE THREAD

**Issue by gmcnaughton** [flyerhzm/bullet#297]
On ActiveRecord 3.2.x, starting with bullet 5.1.0, calling `empty?` on a `has_and_belongs_to_many` association results in the error: `undefined method 'has_cached_counter?' for #<ActiveRecord::Associations::HasAndBelongsToManyAssociation:...>`

For example:
```ruby
class Event < ActiveRecord::Base
  has_and_belongs_to_many :organizers
end

e = Event.create
e.organizers.empty?
# => NoMethodError - undefined method `has_cached_counter?' for #<ActiveRecord::Associations::HasAndBelongsToManyAssociation:0x007f9ba61a3238>:
#  bullet (5.1.0) lib/bullet/active_record3x.rb:121:in `empty?'
#  activerecord (3.2.22.2) lib/active_record/associations/collection_proxy.rb:46:in `empty?'
```

I think this was introduced by https://github.com/flyerhzm/bullet/commit/987c0406a19576404cb12830f50ecd8759a1252f, which was meant to fix #273

**Comment by gmcnaughton** [comment]
Reverting to bullet 5.0.0 makes the issue go away :)

**Comment by flyerhzm** [comment]
@gmcnaughton I have fixed it and released version 5.1.1, please try

**Comment by gmcnaughton** [comment]
5.1.1 fixes the issue for me on AR 3.2.x 👍

Thanks for the quick fix!
