### ISSUE TITLE
doesn't work with activerecord 6.1.0 alpha

### ISSUE THREAD

**Issue by saiqulhaq** [flyerhzm/bullet#517]
https://github.com/flyerhzm/bullet/blob/0844e7a9299c68058938697b7b6f68ceae56e381/lib/bullet.rb#L112

I keep getting `undefined method `[]' for nil:NilClass`

**Comment by owen-c** [comment]
I ran into a similar thing today, but it was only happening in my SystemTests, i.e. the tests that inherit from ApplicationSystemTestCase and run through Capybara. I don't think it is due to ActiveRecord 6.1?

Seems like the Thread.current storage isn't working correctly. The value for whitelist is being initialized on the wrong thread in these cases and then accessed in the Puma server thread during the test where it doesn't exist, thus nil dereference.

I was able to work around this by disabling Bullet for my SystemTests.

**Comment by KapilSachdev** [comment]
@saiqulhaq can you try against master `gem 'bullet', github: 'flyerhzm/bullet'`, #502 added the support for `6.1`.

**Comment by owen-c** [comment]
@KapilSachdev I'm using master, and getting the issue.

**Comment by bslobodin** [comment]
Did anyone have any luck troubleshooting the `Thread` issue mentioned yet?

**Comment by swanson** [comment]
I'm also getting this error, but with ActiveRecord 6.0 -- looks like an issue with this commit: https://github.com/flyerhzm/bullet/commit/9cda9c224a46786ecfa894480c4dd4d304db2adb

**Comment by johan-smits** [comment]
Also see ticket #530 that is requesting a new release.

**Comment by flyerhzm** [comment]
I've released version 6.1.2, please give it a try
